### ISSUE TITLE
When defining module providers, all functions have to be inline otherwise dependencies aren't detected

### ISSUE THREAD

**Issue by rbhalla** [randing89/ngrequire#1]
For example if I had a factory somewhere for `test`, I can't do this:

```
function controllerA(test){}
angular.module('a')
    .controller('controllerA', controllerA);
```

I have to do this:

```
angular.module('a')
    .controller('controllerA', function controllerA(test){});
```

**Comment by randing89** [comment]
Yes. This is a limitation. 
You are welcome to send pull request.

Thanks

**Comment by rbhalla** [comment]
Ok no problem, feel free to close this issue then and I'll try and create a PR for it.
