### ISSUE TITLE
Only the first module definition is parsed (so you can't extend a module)

### ISSUE THREAD

**Issue by rbhalla** [randing89/ngrequire#2]
For example:

```
// a/test.js
angular.module('a')
    .factory('test', function(){})
```

```
// a/test2.js
angular.module('a')
    .factory('test2', function(){})
```

If something relies on module `a`, only the factories provided by `test.js` will be parsed, not `test2.js`

**Comment by randing89** [comment]
If you put both files in path then they will both get parsed

**Comment by rbhalla** [comment]
Hmm, unfortunately that doesn't seem to work for me. I have a generic `src/**/*` set as my path and this problem still exists

**Comment by randing89** [comment]
I've added a test case `spec_multipleProvidersInSameModule.js` just now. In this test case, I am indexing files under `./fixtures/multipleProvidersInSameModule/**/*.js`

After executing `ngRequire.update()` you can see both `a1` and `a2` have been parsed.

**Comment by rbhalla** [comment]
Apologies for the late reply and thanks for writing the test. I'm assuming it must be something to do with my setup though. I'm using this in conjunction with https://github.com/randing89/ngrequire-webpack-plugin so unfortunately I need to do more digging to ascertain the true cause. I will close this issue for now since it seems unrelated to the functionality of this repo.
